name: "Staging deployment" 
on:
  workflow_dispatch:
    inputs:
      PR_number:
        description: 'Pull request number'
        required: true
  pull_request:
    branches:
      - main

jobs:
  create:
    name: 'Create staging and deploy'
    defaults:
      run:
        shell: bash
    
    runs-on: ubuntu-latest
    
    steps:
    # ======================================================
    # Verify that the PR number is valid and belongs to 
    # the repository. The PR's branch is captured as output.
    # ======================================================
    - name: Verify Pull Request Number
      uses: actions/github-script@v5
      id: verify_pr_number
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const response = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: parseInt(core.getInput('PR_number'))
          });
          
          if (!response || response.data.state !== 'open') {
            throw new Error('Pull request is not open or number is not valid!');
          }
          
          console.log("PR ref: " + response.data.head.ref);
          return response.data.head.ref;
      outputs:
        branch_name: ${{ steps.verify_pr_number.outputs.result }}

    # ======================================================
    # Now you can use the branch_name output from the previous step.
    # ======================================================
    - name: Output PR Branch Name
      run: echo "PR branch name is: ${{ steps.verify_pr_number.outputs.branch_name }}"
