name: "Staging deployment" 
on:
  workflow_dispatch:
    inputs:
      PR_number:
        description: 'Pull request number'
        required: true
  pull_request:
    branches:
      - main

jobs:
  create:
    name: 'Create staging and deploy'
    defaults:
      run:
        shell: bash
    
    runs-on: ubuntu-latest
    
    steps:
    # ======================================================
    # Verify that the PR number is valid and belongs to 
    # the repository. The PR's branch is captured as output.
    # ======================================================
    - name: Verify Pull Request Number
      uses: actions/github-script@v5
      id: verify_pr_number
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          // Retrieve the PR number from the inputs
          const prNumber = core.getInput('PR_number');
  
          // Log the PR number to ensure it's being passed correctly
          console.log("Received PR Number:", prNumber);

          // Validate the PR number (it should be a valid integer)
          if (isNaN(parseInt(prNumber))) {
            throw new Error(`Invalid PR Number: ${prNumber}`);
           }

            // Fetch the pull request details
          const response = await github.rest.pulls.get({
               owner: context.repo.owner,
               repo: context.repo.repo,
                pull_number: parseInt(prNumber)
            });

          // Validate if the pull request is open
          if (!response || response.data.state !== 'open') {
            throw new Error('Pull request is not open or number is not valid!');
          }

          // Log the PR branch ref for confirmation
          console.log("PR ref: " + response.data.head.ref);
          return response.data.head.ref;
    

